import type { ReviewCommentWorkflowDependencies } from "./clawsweeper-review-comment-dependencies.js";
import { createReviewCommentIdentity } from "./clawsweeper-review-comment-identity.js";
import { createReviewCommentAutomation } from "./clawsweeper-review-comment-automation.js";
import { createReviewCommentState } from "./clawsweeper-review-comment-state.js";
import { createReviewCommentPublication } from "./clawsweeper-review-comment-publication.js";
import { createReviewCommentLeases } from "./clawsweeper-review-comment-leases.js";

export function createReviewCommentWorkflow(dependencies: ReviewCommentWorkflowDependencies) {
  const identity = createReviewCommentIdentity({ ...dependencies });
  const automation = createReviewCommentAutomation({ ...dependencies, ...identity });
  const state = createReviewCommentState({ ...dependencies, ...identity });
  const publication = createReviewCommentPublication({ ...dependencies, ...identity, ...state });
  const leases = createReviewCommentLeases({
    ...dependencies,
    ...identity,
    ...state,
    ...publication,
  });
  const {
    canPatchReviewComment,
    coverageProofRetryExhaustedRuntimeBudget,
    isCodexReviewCommentBody,
    lockedConversationApplyReason,
    newReviewStartLeaseOwnerForTest,
    recordedLabelSyncCoversUpdate,
    removeCurrentCursorTraceItem,
    renderReviewStartStatusComment,
    reviewArtifactDestination,
    reviewAutomationMarkersFromReport,
    reviewStartLeaseWinnerCommentIdForTest,
    runtimeBudgetExceeded,
    shouldPreserveReviewStartLease,
    supersededReviewPlaceholderCommentIds,
    timeoutWithinRuntimeBudget,
    withReviewStartStatusLease,
    commentId,
    pullHeadShaFromContext,
    fetchIssueReviewComments,
    reviewLeaseRevisionFromReport,
    pullHeadShaFromReport,
    writeCommentPayload,
    repairLoopPassModeFromReport,
    reviewVersionMarkerFromReport,
    reviewStructuralPullStateFromContext,
    exactReviewQueueAuthorityFromEnv,
    postReviewStartStatusComment,
    deleteOwnedDedicatedReviewStartLease,
    freshDedicatedReviewStartLeases,
    issueReviewCommentState,
    PATCHABLE_REVIEW_COMMENT_AUTHORS,
    staleReviewCommentSyncReason,
    newerDurableReviewTupleVerified,
    reviewCommentHasCloseVerdictForCanonical,
    issueReviewComment,
    markedReviewCommentBody,
    commentBodyMatches,
    reviewCommentHashMatches,
    commentUpdatedAt,
    cleanupSupersededReviewPlaceholderComments,
    reviewStartLeaseOwner,
    commentBody,
    freshPullRequestReviewHead,
    stalePullRequestReviewHead,
    syncStalePullRequestReviewLabels,
    stalePullRequestReviewComment,
    updateReviewCommentMetadata,
    upsertReviewComment,
    ensureCloseAppliedComment,
  } = { ...identity, ...automation, ...state, ...publication, ...leases };
  return {
    canPatchReviewComment,
    coverageProofRetryExhaustedRuntimeBudget,
    isCodexReviewCommentBody,
    lockedConversationApplyReason,
    newReviewStartLeaseOwnerForTest,
    recordedLabelSyncCoversUpdate,
    removeCurrentCursorTraceItem,
    renderReviewStartStatusComment,
    reviewArtifactDestination,
    reviewAutomationMarkersFromReport,
    reviewStartLeaseWinnerCommentIdForTest,
    runtimeBudgetExceeded,
    shouldPreserveReviewStartLease,
    supersededReviewPlaceholderCommentIds,
    timeoutWithinRuntimeBudget,
    withReviewStartStatusLease,
    commentId,
    pullHeadShaFromContext,
    fetchIssueReviewComments,
    reviewLeaseRevisionFromReport,
    pullHeadShaFromReport,
    writeCommentPayload,
    repairLoopPassModeFromReport,
    reviewVersionMarkerFromReport,
    reviewStructuralPullStateFromContext,
    exactReviewQueueAuthorityFromEnv,
    postReviewStartStatusComment,
    deleteOwnedDedicatedReviewStartLease,
    freshDedicatedReviewStartLeases,
    issueReviewCommentState,
    PATCHABLE_REVIEW_COMMENT_AUTHORS,
    staleReviewCommentSyncReason,
    newerDurableReviewTupleVerified,
    reviewCommentHasCloseVerdictForCanonical,
    issueReviewComment,
    markedReviewCommentBody,
    commentBodyMatches,
    reviewCommentHashMatches,
    commentUpdatedAt,
    cleanupSupersededReviewPlaceholderComments,
    reviewStartLeaseOwner,
    commentBody,
    freshPullRequestReviewHead,
    stalePullRequestReviewHead,
    syncStalePullRequestReviewLabels,
    stalePullRequestReviewComment,
    updateReviewCommentMetadata,
    upsertReviewComment,
    ensureCloseAppliedComment,
  };
}
