import type { LabelSynchronizationDependencies } from "./clawsweeper-label-dependencies.js";
import { createLabelSelectionPolicy } from "./clawsweeper-label-selection.js";
import { createLabelMutationOperations } from "./clawsweeper-label-mutations.js";
import { createLabelSyncOperations } from "./clawsweeper-label-operations.js";

export function createLabelSynchronization(dependencies: LabelSynchronizationDependencies) {
  const selection = createLabelSelectionPolicy({ ...dependencies });
  const mutations = createLabelMutationOperations({ ...dependencies, ...selection });
  const operations = createLabelSyncOperations({ ...dependencies, ...selection, ...mutations });
  const {
    impactLabelSchemeForTest,
    impactLabelsForTest,
    isGitHubLabelAlreadyExistsErrorForTest,
    isGitHubLabelCapacityErrorForTest,
    isMissingGitHubLabelErrorForTest,
    issueAdvisoryLabelsForTest,
    maturityLabelSchemeForTest,
    maturityLabelsForTest,
    mergeRiskLabelSchemeForTest,
    mergeRiskLabelsForTest,
    priorityLabelSchemeForTest,
    priorityLabelsForTest,
    prRatingLabelSchemeForTest,
    prRatingLabelsForTest,
    realBehaviorProofMediaLabelsForTest,
    realBehaviorProofSufficientLabelsForTest,
    syncBulkFilerLabelForTest,
    telegramVisibleProofLabelsForTest,
    beginIssueLabelMutationBatch,
    discardIssueLabelMutationBatch,
    flushIssueLabelMutationBatch,
    addIssueLabel,
    ensureIdeaArchiveLabel,
    isGoodFirstIssue,
    isIssueAdvisoryLabel,
    issueAdvisoryLabelStateFromReport,
    labelAlreadyExistsError,
    nextImpactLabels,
    nextIssueAdvisoryLabels,
    nextMaturityLabels,
    nextMergeRiskLabels,
    nextPriorityLabels,
    nextRealBehaviorProofMediaLabels,
    nextRealBehaviorProofSufficientLabels,
    nextTelegramVisibleProofLabels,
    removeIssueLabel,
    syncBulkFilerLabel,
    syncFeatureShowcaseLabel,
    syncImpactLabels,
    syncIssueAdvisoryLabels,
    syncMaturityLabels,
    syncMergeRiskLabels,
    syncPriorityLabel,
    syncPrRatingLabel,
    syncPrStatusLabel,
    syncRealBehaviorProofMediaLabels,
    syncRealBehaviorProofSufficientLabel,
    syncTelegramVisibleProofLabel,
  } = { ...selection, ...mutations, ...operations };
  return {
    impactLabelSchemeForTest,
    impactLabelsForTest,
    isGitHubLabelAlreadyExistsErrorForTest,
    isGitHubLabelCapacityErrorForTest,
    isMissingGitHubLabelErrorForTest,
    issueAdvisoryLabelsForTest,
    maturityLabelSchemeForTest,
    maturityLabelsForTest,
    mergeRiskLabelSchemeForTest,
    mergeRiskLabelsForTest,
    priorityLabelSchemeForTest,
    priorityLabelsForTest,
    prRatingLabelSchemeForTest,
    prRatingLabelsForTest,
    realBehaviorProofMediaLabelsForTest,
    realBehaviorProofSufficientLabelsForTest,
    syncBulkFilerLabelForTest,
    telegramVisibleProofLabelsForTest,
    beginIssueLabelMutationBatch,
    discardIssueLabelMutationBatch,
    flushIssueLabelMutationBatch,
    addIssueLabel,
    ensureIdeaArchiveLabel,
    isGoodFirstIssue,
    isIssueAdvisoryLabel,
    issueAdvisoryLabelStateFromReport,
    labelAlreadyExistsError,
    nextImpactLabels,
    nextIssueAdvisoryLabels,
    nextMaturityLabels,
    nextMergeRiskLabels,
    nextPriorityLabels,
    nextRealBehaviorProofMediaLabels,
    nextRealBehaviorProofSufficientLabels,
    nextTelegramVisibleProofLabels,
    removeIssueLabel,
    syncBulkFilerLabel,
    syncFeatureShowcaseLabel,
    syncImpactLabels,
    syncIssueAdvisoryLabels,
    syncMaturityLabels,
    syncMergeRiskLabels,
    syncPriorityLabel,
    syncPrRatingLabel,
    syncPrStatusLabel,
    syncRealBehaviorProofMediaLabels,
    syncRealBehaviorProofSufficientLabel,
    syncTelegramVisibleProofLabel,
  };
}
